### ISSUE TITLE
Update CI plan to test for Python versions 3.9 and 3.10

### ISSUE THREAD

**Issue by Frost45** [EducationalTestingService/gector#4]
Since currently, this repo uses `allennlp=0.9.0` which in turn uses `spacy=2.1.9`, it is incompatible with Python v3.9 and v3.10. This needs to be added to the CI plan in subsequent PRs once `allennlp` is unpinned.

**Comment by damien2012eng** [comment]
This issue can be closed after the unpin PR merged. Please see a successful built [here](https://github.com/EducationalTestingService/gector/pull/14/checks).
